/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContYoutubeRouteImport } from './routes/ContYoutube'
import { Route as ClasesRouteImport } from './routes/clases'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as FormacionesRouteImport } from './routes/formaciones'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as PagosRouteImport } from './routes/pagos'
import { Route as ServiciosRouteImport } from './routes/servicios'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SobreMiRouteImport } from './routes/sobre-mi'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminNuevoRouteImport } from './routes/admin/nuevo'
import { Route as AdminPagosRouteImport } from './routes/admin/pagos'
import { Route as FormacionesIndexRouteImport } from './routes/formaciones/index'
import { Route as FormacionesFormacionIdRouteImport } from './routes/formaciones/$formacionId'
import { Route as FormacionesClasesRouteImport } from './routes/formaciones/clases'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AdminEditarIdRouteImport } from './routes/admin/editar.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContYoutubeRoute = ContYoutubeRouteImport.update({
  id: '/ContYoutube',
  path: '/ContYoutube',
  getParentRoute: () => rootRouteImport,
} as any)
const ClasesRoute = ClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacionesRoute = FormacionesRouteImport.update({
  id: '/formaciones',
  path: '/formaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosRoute = PagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiciosRoute = ServiciosRouteImport.update({
  id: '/servicios',
  path: '/servicios',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreMiRoute = SobreMiRouteImport.update({
  id: '/sobre-mi',
  path: '/sobre-mi',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNuevoRoute = AdminNuevoRouteImport.update({
  id: '/admin/nuevo',
  path: '/admin/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPagosRoute = AdminPagosRouteImport.update({
  id: '/admin/pagos',
  path: '/admin/pagos',
  getParentRoute: () => rootRouteImport,
} as any)
const FormacionesIndexRoute = FormacionesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormacionesRoute,
} as any)
const FormacionesFormacionIdRoute = FormacionesFormacionIdRouteImport.update({
  id: '/$formacionId',
  path: '/$formacionId',
  getParentRoute: () => FormacionesRoute,
} as any)
const FormacionesClasesRoute = FormacionesClasesRouteImport.update({
  id: '/clases',
  path: '/clases',
  getParentRoute: () => FormacionesRoute,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminEditarIdRoute = AdminEditarIdRouteImport.update({
  id: '/admin/editar/$id',
  path: '/admin/editar/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ContYoutube': typeof ContYoutubeRoute
  '/clases': typeof ClasesRoute
  '/contacto': typeof ContactoRoute
  '/formaciones': typeof FormacionesRouteWithChildren
  '/mcp': typeof McpRoute
  '/pagos': typeof PagosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/nuevo': typeof AdminNuevoRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/formaciones/$formacionId': typeof FormacionesFormacionIdRoute
  '/formaciones/clases': typeof FormacionesClasesRoute
  '/admin/': typeof AdminIndexRoute
  '/formaciones/': typeof FormacionesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/editar/$id': typeof AdminEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ContYoutube': typeof ContYoutubeRoute
  '/clases': typeof ClasesRoute
  '/contacto': typeof ContactoRoute
  '/mcp': typeof McpRoute
  '/pagos': typeof PagosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/nuevo': typeof AdminNuevoRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/formaciones/$formacionId': typeof FormacionesFormacionIdRoute
  '/formaciones/clases': typeof FormacionesClasesRoute
  '/admin': typeof AdminIndexRoute
  '/formaciones': typeof FormacionesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/editar/$id': typeof AdminEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ContYoutube': typeof ContYoutubeRoute
  '/clases': typeof ClasesRoute
  '/contacto': typeof ContactoRoute
  '/formaciones': typeof FormacionesRouteWithChildren
  '/mcp': typeof McpRoute
  '/pagos': typeof PagosRoute
  '/servicios': typeof ServiciosRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre-mi': typeof SobreMiRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/nuevo': typeof AdminNuevoRoute
  '/admin/pagos': typeof AdminPagosRoute
  '/formaciones/$formacionId': typeof FormacionesFormacionIdRoute
  '/formaciones/clases': typeof FormacionesClasesRoute
  '/admin/': typeof AdminIndexRoute
  '/formaciones/': typeof FormacionesIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/editar/$id': typeof AdminEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ContYoutube'
    | '/clases'
    | '/contacto'
    | '/formaciones'
    | '/mcp'
    | '/pagos'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/dashboard'
    | '/admin/nuevo'
    | '/admin/pagos'
    | '/formaciones/$formacionId'
    | '/formaciones/clases'
    | '/admin/'
    | '/formaciones/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ContYoutube'
    | '/clases'
    | '/contacto'
    | '/mcp'
    | '/pagos'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/dashboard'
    | '/admin/nuevo'
    | '/admin/pagos'
    | '/formaciones/$formacionId'
    | '/formaciones/clases'
    | '/admin'
    | '/formaciones'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/ContYoutube'
    | '/clases'
    | '/contacto'
    | '/formaciones'
    | '/mcp'
    | '/pagos'
    | '/servicios'
    | '/sitemap.xml'
    | '/sobre-mi'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/dashboard'
    | '/admin/nuevo'
    | '/admin/pagos'
    | '/formaciones/$formacionId'
    | '/formaciones/clases'
    | '/admin/'
    | '/formaciones/'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContYoutubeRoute: typeof ContYoutubeRoute
  ClasesRoute: typeof ClasesRoute
  ContactoRoute: typeof ContactoRoute
  FormacionesRoute: typeof FormacionesRouteWithChildren
  McpRoute: typeof McpRoute
  PagosRoute: typeof PagosRoute
  ServiciosRoute: typeof ServiciosRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreMiRoute: typeof SobreMiRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminNuevoRoute: typeof AdminNuevoRoute
  AdminPagosRoute: typeof AdminPagosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  AdminEditarIdRoute: typeof AdminEditarIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ContYoutube': {
      id: '/ContYoutube'
      path: '/ContYoutube'
      fullPath: '/ContYoutube'
      preLoaderRoute: typeof ContYoutubeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clases': {
      id: '/clases'
      path: '/clases'
      fullPath: '/clases'
      preLoaderRoute: typeof ClasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formaciones': {
      id: '/formaciones'
      path: '/formaciones'
      fullPath: '/formaciones'
      preLoaderRoute: typeof FormacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos': {
      id: '/pagos'
      path: '/pagos'
      fullPath: '/pagos'
      preLoaderRoute: typeof PagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/servicios': {
      id: '/servicios'
      path: '/servicios'
      fullPath: '/servicios'
      preLoaderRoute: typeof ServiciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-mi': {
      id: '/sobre-mi'
      path: '/sobre-mi'
      fullPath: '/sobre-mi'
      preLoaderRoute: typeof SobreMiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/nuevo': {
      id: '/admin/nuevo'
      path: '/admin/nuevo'
      fullPath: '/admin/nuevo'
      preLoaderRoute: typeof AdminNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pagos': {
      id: '/admin/pagos'
      path: '/admin/pagos'
      fullPath: '/admin/pagos'
      preLoaderRoute: typeof AdminPagosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/formaciones/': {
      id: '/formaciones/'
      path: '/'
      fullPath: '/formaciones/'
      preLoaderRoute: typeof FormacionesIndexRouteImport
      parentRoute: typeof FormacionesRoute
    }
    '/formaciones/$formacionId': {
      id: '/formaciones/$formacionId'
      path: '/$formacionId'
      fullPath: '/formaciones/$formacionId'
      preLoaderRoute: typeof FormacionesFormacionIdRouteImport
      parentRoute: typeof FormacionesRoute
    }
    '/formaciones/clases': {
      id: '/formaciones/clases'
      path: '/clases'
      fullPath: '/formaciones/clases'
      preLoaderRoute: typeof FormacionesClasesRouteImport
      parentRoute: typeof FormacionesRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/editar/$id': {
      id: '/admin/editar/$id'
      path: '/admin/editar/$id'
      fullPath: '/admin/editar/$id'
      preLoaderRoute: typeof AdminEditarIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FormacionesRouteChildren {
  FormacionesFormacionIdRoute: typeof FormacionesFormacionIdRoute
  FormacionesClasesRoute: typeof FormacionesClasesRoute
  FormacionesIndexRoute: typeof FormacionesIndexRoute
}

const FormacionesRouteChildren: FormacionesRouteChildren = {
  FormacionesFormacionIdRoute: FormacionesFormacionIdRoute,
  FormacionesClasesRoute: FormacionesClasesRoute,
  FormacionesIndexRoute: FormacionesIndexRoute,
}

const FormacionesRouteWithChildren = FormacionesRoute._addFileChildren(
  FormacionesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContYoutubeRoute: ContYoutubeRoute,
  ClasesRoute: ClasesRoute,
  ContactoRoute: ContactoRoute,
  FormacionesRoute: FormacionesRouteWithChildren,
  McpRoute: McpRoute,
  PagosRoute: PagosRoute,
  ServiciosRoute: ServiciosRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreMiRoute: SobreMiRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminNuevoRoute: AdminNuevoRoute,
  AdminPagosRoute: AdminPagosRoute,
  AdminIndexRoute: AdminIndexRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  AdminEditarIdRoute: AdminEditarIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
